### ISSUE TITLE
build error with ffmpeg 2.8.8

### ISSUE THREAD

**Issue by kleph** [Polochon-street/bliss#28]
Hi, 

First the disclaimer, I'm trying to build bliss on an unsupported distribution, gentoo \~amd64. (~ kinda means "testing")
For now, it still use ffmpeg 2.8.8 since build regressions with versions >= 3 are not all fixed (https://bugs.gentoo.org/show_bug.cgi?id=574788).

It does not build with ffmpeg 2.8:
```
[  6%] Building C object CMakeFiles/bliss.dir/src/decode.c.o
/home/kleph/sources/bliss/src/decode.c: In function ‘bl_audio_decode’:
/home/kleph/sources/bliss/src/decode.c:15:2: error: unknown type name ‘AVCodecParameters’
  AVCodecParameters *codecpar = NULL;
  ^
/home/kleph/sources/bliss/src/decode.c:62:43: error: ‘AVStream’ has no member named ‘codecpar’
  codecpar = context->streams[audio_stream]->codecpar;
                                           ^
/home/kleph/sources/bliss/src/decode.c:76:30: error: request for member ‘sample_rate’ in something not a structure or union
  song->sample_rate = codecpar->sample_rate;
                              ^
/home/kleph/sources/bliss/src/decode.c:80:62: error: request for member ‘format’ in something not a structure or union
  song->nb_bytes_per_sample = av_get_bytes_per_sample(codecpar->format);
                                                              ^
/home/kleph/sources/bliss/src/decode.c:81:27: error: request for member ‘channels’ in something not a structure or union
  song->channels = codecpar->channels;
                           ^
/home/kleph/sources/bliss/src/decode.c:110:13: error: request for member ‘format’ in something not a structure or union
  if(codecpar->format != AV_SAMPLE_FMT_S16 &&
             ^
/home/kleph/sources/bliss/src/decode.c:111:11: error: request for member ‘format’ in something not a structure or union
   codecpar->format != AV_SAMPLE_FMT_S16P) {
           ^
/home/kleph/sources/bliss/src/decode.c:116:56: error: request for member ‘channel_layout’ in something not a structure or union
   av_opt_set_int(swr_ctx, "in_channel_layout", codecpar->channel_layout, 0);
                                                        ^
/home/kleph/sources/bliss/src/decode.c:118:59: error: request for member ‘format’ in something not a structure or union
   av_opt_set_sample_fmt(swr_ctx, "in_sample_fmt", codecpar->format, 0);
                                                           ^
/home/kleph/sources/bliss/src/decode.c:120:57: error: request for member ‘channel_layout’ in something not a structure or union
   av_opt_set_int(swr_ctx, "out_channel_layout", codecpar->channel_layout, 0);
                                                         ^
/home/kleph/sources/bliss/src/decode.c:192:46: error: request for member ‘format’ in something not a structure or union
  is_planar = av_sample_fmt_is_planar(codecpar->format);
                                              ^
/home/kleph/sources/bliss/src/decode.c:216:4: warning: implicit declaration of function ‘avcodec_send_packet’ [-Wimplicit-function-declaration]
    ret = avcodec_send_packet(codec_context, &avpkt);
    ^
/home/kleph/sources/bliss/src/decode.c:217:4: warning: implicit declaration of function ‘avcodec_receive_frame’ [-Wimplicit-function-declaration]
    got_frame = !avcodec_receive_frame(codec_context, decoded_frame);
    ^
/home/kleph/sources/bliss/src/decode.c:230:14: error: request for member ‘format’ in something not a structure or union
      codecpar->format,
              ^
make[2]: *** [CMakeFiles/bliss.dir/build.make:87: CMakeFiles/bliss.dir/src/decode.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/bliss.dir/all] Error 2
make: *** [Makefile:161: all] Error 2
```

I'm not sure it's a real issue as it will probably solve itself with ffmpeg-2.8 natural disappearance.
Maybe just a warning about version of libavcodec or ffmpeg >= 3 in the readme or with cmake should be enough.

**Comment by Phyks** [comment]
Did you try with the latest git branch? Looks similar to https://github.com/Polochon-street/bliss/issues/26 (sorry, in French) and it is supposed to be solved recently.

Also, I built it recently on Arch which is quite cutting edge without issues, and have just tried compiling it on Mac OS with `ffmpeg == 3.1.3` without issues as well.

**Comment by kleph** [comment]
Thanks, it worked.
My bad, on this computer I forgot to pull the lastest changes and did not see #26 ...
Sorry for the noise ;p
